"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['auth.py']
DATA_FILES = ['db.py', 'p2.py']
OPTIONS = {
    'packages': ['certifi',]
}

setup(
    name = 'MELODIO',
    version = '0.0001',
    author = 'finlandcowboy',
install_requires=[
        "tkinter",
        "psycopg2"
    ],

    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
